
import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script'; // Importa el componente Script de Next.js
import { GA_TRACKING_ID } from '../lib/gtag'; // Importa tu ID de seguimiento

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "izmanagement",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      {/* Scripts de Google Analytics
        Se cargan de forma asíncrona usando la estrategia recomendada por Next.js
        para no bloquear el renderizado de la página.
      */}
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`}
      />
      <Script
        id="gtag-init"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_TRACKING_ID}', {
              page_path: window.location.pathname,
            });
          `,
        }}
      />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
